const fs = require('fs');
const parse = require('json-templates');
const md5 = require('md5');
const archiver = require('archiver');

const templateText = fs.readFileSync('sprite-template.json', 'utf8');
const template = parse(templateText);

const svgPath = 'costumes/SVG/';

const interval = 64;
const yBaseline = -132;
const xEnds = 192;

const spriteDefs = [
    {
        name: 'key-up',
        x: -xEnds + interval,
        y: yBaseline + interval,
        uid: 'nX%+n+T4j8v~HNn#aTq;'
        // Unique IDs were generated by Blockly.utils.genUid() from scratch-blocks/core/utils.js
        // They should not be changed.
    },
    {
        name: 'key-left',
        x: -xEnds,
        y: yBaseline,
        uid: 'wA@DV3Q5-ij17YO[_{$i'
    },
    {
        name: 'key-down',
        x: -xEnds + interval,
        y: yBaseline,
        uid: 'VI]k.Kt|tx;)Fe9u^$.B'
    },
    {
        name: 'key-right',
        x: -xEnds + interval * 2,
        y: yBaseline,
        uid: '3exdMTroq0G9L09OsrZ_'
    },
    {
        name: 'key-space',
        x: 0,
        y: yBaseline,
        uid: 'h5x6|}}wAW|y9t#H@RKs'
    },
    {
        name: 'key-z',
        x: xEnds - interval,
        y: yBaseline,
        uid: 'b-JNd*xg9Dc3VbFc,ezQ'
    },
    {
        name: 'key-x',
        x: xEnds,
        y: yBaseline,
        uid: 'AVgU)wJ`uB@@zsOX1hkP'
    },
];

function buildSprite(spriteDef, onCompleted) {
    // MD5
    const md5Normal = md5(fs.readFileSync(svgPath + spriteDef.name + '.svg'));
    const md5Pressed = md5(fs.readFileSync(svgPath + spriteDef.name + '-pressed.svg'));
    // variables for template
    const variables = {
        name : spriteDef.name,
        x : spriteDef.x,
        y : spriteDef.y,
        svgHash : md5Normal,
        svgHashPressed : md5Pressed,
        'event-name': spriteDef.name + ' pressed',
        'event-id': spriteDef.uid,
    };
    
    // zip
    var archive = archiver.create('zip', {});
    var output = fs.createWriteStream('sprites/' + spriteDef.name + '.sprite3');
    archive.pipe(output);
    
    // 2 svg files and json from template.
    archive.file(svgPath + spriteDef.name + '.svg', { name: md5Normal + '.svg' });
    archive.file(svgPath + spriteDef.name + '-pressed.svg', { name: md5Pressed + '.svg' });
    archive.append(template(variables), { name: 'sprite.json' });
    
    archive.finalize();
    output.on('close', onCompleted);
}

function next() {
    const def = spriteDefs.shift();
    if (def) {
        buildSprite(def, next);
    }
}

next();
